[package]
name = "wg-mesh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
futures = "0.3.28"
ipnet = "2.8.0"
netlink-packet-core = "0.7.0"
nix = "0.27.1"
resolv-conf = "0.7.0"
rsdns = { version = "0.15.0", features = [ "net-tokio" ] }
rtnetlink = "0.13.1"
thiserror = "1.0.49"
tokio = { version = "1.31.0", features = ["full"] }
wireguard-control = "1.5.0"
