[package]
name = "wg-mesh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
ipnet = "2.7.2"
nix = "0.26.2"
rsdns = { version = "0.15.0", features = [ "net-tokio" ] }
rtnetlink = "0.12.0"
thiserror = "1.0.41"
tokio = { version = "1.28.0", features = ["full"] }
wireguard-control = "1.5.0"
